<div class="apelos-container">
    <div class="apelo">
        <div class="ico">
        <img src='<?php echo $block->getViewFileUrl('Magento_Theme::images/con.svg'); ?>' alt="image-icon" width="40" height="40">
        </div>
        <div class="desc">
            Parcele em até 12x<p>sem juros no cartão</p>
        </div>
    </div>
    <div class="apelo">
        <div class="ico">
            <img src='<?php echo $block->getViewFileUrl('Magento_Theme::images/truck.svg'); ?>' alt="image-icon" width="40" height="40">
        </div>
        <div class="desc">
            Frete grátis *<p>*compras acima de R$200</p>
        </div>
    </div>
    <div class="apelo">
        <div class="ico">
            <img src='<?php echo $block->getViewFileUrl('Magento_Theme::images/con.svg'); ?>' alt="image-icon" width="40" height="40">
        </div>
        <div class="desc">
            5% de desconto<p>pagando via boleto</p>
        </div>
    </div>
    <div class="apelo no-border">
        <div class="ico">
            <img src='<?php echo $block->getViewFileUrl('Magento_Theme::images/shield.svg'); ?>' alt="image-icon" width="40" height="40">
        </div>
        <div class="desc">
            Compra segura<p>seus dados protegidos</p>
        </div>
    </div>
</div>